# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:categories/:year/:month/:title.html
relative_permalinks: false

# Setup
title:               Flavours of a Nerd
tagline:             'a glob of incoherent, unanticipated blabber'
description:         "A reserved space to show my views, progress and checkpoints that relate to technical, spiritual and artsy stuff I do."
url:                 http://sizhky.github.io/
baseurl:             
paginate:            2
show_drafts:         true
# About/contact
author:
  name:              Yeshwanth
  url:               https://twitter.com/sizhky
  email:             1992chinna@gmail.com

# Custom vars
version:             1.0.0
gems: [jekyll-paginate, jekyll-picture-tag]

# Conversion
markdown:    kramdown
highlighter: rouge